# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.misc_api import MiscApi


class TestMiscApi(unittest.TestCase):
    """MiscApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiscApi()

    def tearDown(self) -> None:
        pass

    def test_v2_ping_get(self) -> None:
        """Test case for v2_ping_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
