# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v2_network_network_id_evm_cross_transactions_get200_response_items_inner_data import V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData

class TestV2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData(unittest.TestCase):
    """V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData:
        """Test V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData`
        """
        model = V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData()
        if include_optional:
            return V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData(
                queue_index = '',
                requested_gas_limit = '',
                l1_tx_origin = '',
                message_nonce = '',
                message_hash = '',
                source_hash = '',
                withdrawal_hash = '',
                proof_tx_hash = '',
                proof_tx_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                success = True
            )
        else:
            return V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData(
        )
        """

    def testV2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData(self):
        """Test V2NetworkNetworkIdEvmCrossTransactionsGet200ResponseItemsInnerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
