# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v2_network_network_id_staking_address_address_id_overview_get200_response_inner_stake import V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake

class TestV2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake(unittest.TestCase):
    """V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake:
        """Test V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake`
        """
        model = V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake()
        if include_optional:
            return V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake(
                staked_in_validations = '',
                staked_in_delegations = '',
                not_staked = ''
            )
        else:
            return V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake(
                staked_in_validations = '',
                staked_in_delegations = '',
                not_staked = '',
        )
        """

    def testV2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake(self):
        """Test V2NetworkNetworkIdStakingAddressAddressIdOverviewGet200ResponseInnerStake"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
