# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.evm_api import EVMApi


class TestEVMApi(unittest.TestCase):
    """EVMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EVMApi()

    def tearDown(self) -> None:
        pass

    def test_v2_network_network_id_evm_chain_id_blocks_get(self) -> None:
        """Test case for v2_network_network_id_evm_chain_id_blocks_get

        """
        pass

    def test_v2_network_network_id_evm_chain_id_etherscanwildcard_get(self) -> None:
        """Test case for v2_network_network_id_evm_chain_id_etherscanwildcard_get

        """
        pass

    def test_v2_network_network_id_evm_chain_id_etherscanwildcard_post(self) -> None:
        """Test case for v2_network_network_id_evm_chain_id_etherscanwildcard_post

        """
        pass

    def test_v2_network_network_id_evm_cross_transactions_get(self) -> None:
        """Test case for v2_network_network_id_evm_cross_transactions_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
