# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.staking_api import StakingApi


class TestStakingApi(unittest.TestCase):
    """StakingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StakingApi()

    def tearDown(self) -> None:
        pass

    def test_v2_network_network_id_staking_address_address_id_get(self) -> None:
        """Test case for v2_network_network_id_staking_address_address_id_get

        """
        pass

    def test_v2_network_network_id_staking_address_address_id_overview_get(self) -> None:
        """Test case for v2_network_network_id_staking_address_address_id_overview_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
