# coding: utf-8

"""
    Avascan API

    Avalanche multi-chain explorer API docs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v2_ping_get200_response import V2PingGet200Response

class TestV2PingGet200Response(unittest.TestCase):
    """V2PingGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2PingGet200Response:
        """Test V2PingGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2PingGet200Response`
        """
        model = V2PingGet200Response()
        if include_optional:
            return V2PingGet200Response(
                ping = 'pong'
            )
        else:
            return V2PingGet200Response(
                ping = 'pong',
        )
        """

    def testV2PingGet200Response(self):
        """Test V2PingGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
